name: rescuerapp
description: First ait application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # app diagnosting
  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  firebase_performance: ^0.4.2
  # state management
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3+1
  # navigation
  auto_route: ^0.6.9
  stacked_services: ^0.5.4+4
  # inversion of control
  get_it:
  injectable:
  flutter_hooks:
  observable_ish:
  image_picker: ^0.6.7+12
  http: ^0.12.2
  animations: ^1.1.2
  # device
  settings_ui: ^0.4.0
  device_info: ^0.4.2+9
  package_info: ^0.4.3
  shared_preferences: ^0.5.12+2
  # localization
  easy_localization: ^2.3.3
  easy_localization_loader:
    path: packages/easy_localization_loader

  flutter_svg: ^0.19.1
  logger: ^0.9.4
  theme_mode_handler: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner:
  auto_route_generator:
  injectable_generator:
  json_serializable:
  mockito:

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
